<main>
        <section class="presentation">
            <h2 class="sec01 titre_homepage"><?= $presentation->titre ?>.</h2>
            <p>🦸🏽‍♂️ Un petit résumé.</p>
            <div class="separation"></div>
            <article>
                <div class="photo revelation fadeInLeft">
                    <img src="img/MeBlack.jpg" alt="Photo de Omar Belaid">
                </div>
                <div class="text revelation fadeInRight">
                    <p><?= $presentation->contenu ?></p>
                </div>
            </article>
        </section>

        <section class="competences">
            <h2 class="sec02 titre_homepage">Mes compétences.</h2>
            <p>👨🏽‍🔧 A votre service.</p>
            <div class="separation"></div>
            <article>
                <div>
                    <i class="devicon-html5-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-css3-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-php-plain colored revelation animation fadeInUp"></i>
                    <i class="devicon-javascript-plain colored revelation animation fadeInRight"></i>
                    <i class="devicon-jquery-plain-wordmark colored revelation animation fadeInRight"></i>
                </div>

                <div>
                    <i class="devicon-mysql-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-bootstrap-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-visualstudio-plain-wordmark colored revelation animation fadeInUp"></i>
                    <i class="devicon-wordpress-plain-wordmark colored revelation animation fadeInRight"></i>
                    <i class="devicon-github-plain-wordmark colored revelation animation fadeInRight"></i>
                </div>
            </article>
        </section>

        <section class="experience">
            <div class="experience_container">
                <h2 class="sec03 titre_homepage">Mon Parcours</h2>
                <div class="divpro"><span id="pro" class="pro">👷🏽‍♂️ Professionnel</span></div>
                <div class="separation"></div>

                <div id="timeline">
                    <div id="cest_professionnel" class="cest_professionnel">

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>SEPT 2021<br />
                                    à <br />
                                    Ce jour</p>
                            </div>
                            <div class="right">
                                <div class="content">

                                    <h3><i class="fas fa-briefcase"></i>DÉVELOPPEUR WEB FULL-STACK</h3>
                                    <div class="date">
                                        SEPT 2021 à Ce jour
                                    </div>
                                    <div class="place">Firstcom | New Media (13)</div>


                                    <ul>
                                        <li>Etudes des demandes clients.</li>
                                        <li>Création complète de sites internet via HTML 5, CSS 3, PHP, SQL, JavaScript, divers CMS et outils de versioning.</li>
                                        <li>Ajout de nouvelles fonctionalités sur sites existants.</li>
                                        <li>Maintenance.</li>
                                    </ul>

                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MAI 2021<br />
                                    à <br />
                                    SEPT 2021</p>
                            </div>
                            <div class="right">
                                <div class="content">

                                    <h3><i class="fas fa-briefcase"></i>DÉVELOPPEUR WEB FULL-STACK</h3>
                                    <div class="date">
                                        MAI 2021 à SEPT 2021
                                    </div>
                                    <div class="place">3W Academy Marseille (13)</div>


                                    <ul>
                                        <li>Etude et utilisation des langages HTML 5, CSS 3, PHP 7, SQL, JavaScript, Ajax, JQuery pour la création complète de sites internet.</li>
                                        <li>Etude et réalisation de maquettes responsives . Etude et conception de base de données MySQL.</li>
                                        <li>Respect des bonnes pratiques de développement.</li>
                                    </ul>

                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MAI 2019<br />
                                    à <br />
                                    SEPT 2020</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>RESPONSABLE D'EXPLOITATION</h3>
                                    <div class="date">MAI 2019 à SEPT 2020</div>
                                    <div class="place">Bansard International Marseille (13)</div>

                                    <ul>
                                        <li>Supervise et coordonne l'activité du service d'exploitation de transport international, dans ses dimensions techniques, commerciales, sociales et financières, selon la réglementation du transport international, les règles de sécurité et dans un objectif de qualité (service, coût, délais).</li>
                                        <li>Dirige des équipes d'un site d'exploitation (techniciens exploitants, conducteurs, agents de quai, ...).</li>
                                        <li>Superviser les plannings du service à partir des carnets de commande</li>
                                        <li>Coordonner l'activité d'une équipe</li>
                                        <li>Concevoir les modalités de prestation et les conditions de réalisation de transport avec la clientèle ou les prestataires</li>
                                        <li>Mener des opérations de transport en relation avec une clientèle internationale</li>
                                        <li>Organiser et coordonner le circuit des informations avec les autres services</li>
                                        <li>Analyser les données d'activité du service et identifier des axes d'amélioration</li>
                                        <li>Suivre un budget</li>
                                        <li>Traiter des dossiers de contentieux (litiges, réclamations ...)</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>SEPT 2018 <br />
                                    à <br />
                                    AVRIL 2019</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>ORGANISATEUR TRANSPORT INTERNATIONAL</h3>
                                    <div class="date">SEPT 2018 à AVRIL 2019</div>
                                    <div class="place">Stefover Vitrolles (13)</div>

                                    <ul>
                                        <li>Conseiller un client sur la circulation internationale des marchandises</li>
                                        <li>Codifier la marchandise à partir du descriptif fourni par le client</li>
                                        <li>Collecter les documents d'expédition de la marchandise et constituer le dossier de la prestation (transit, douane)</li>
                                        <li>Réaliser et contrôler les documents liés à la circulation internationale de la marchandise (facture douanière, Déclaration Administrative Unique -DAU-, lettre de crédit, ...)</li>
                                        <li>Suivre l'acheminement des marchandises, informer le client sur le déroulement et présenter des solutions en cas d'anomalies</li>
                                        <li>Rechercher des informations documentaires</li>
                                        <li>Gérer l'activité logistique</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MARS 2018 <br />
                                    à <br />
                                    AOUT 2018</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>RESPONSABLE TRANSPORT</h3>
                                    <div class="date">MARS 2018 à AOUT 2018</div>
                                    <div class="place">Vectorys Marignane (13)</div>

                                    <ul>
                                        <li>Supervise et coordonne l'activité du service d'exploitation de transport régional et portuaire dans ses dimensions techniques, selon la réglementation du transport international, les règles de sécurité et dans un objectif de qualité (service, coût, délais).</li>
                                        <li>En lien avec le GPMM (Port autonome de Marseille)</li>
                                        <li>Dirige des équipes d'un site d'exploitation (techniciens exploitants, conducteurs, agents de quai, ...).</li>
                                        <li>Superviser les plannings du service à partir des carnets de commande</li>
                                        <li>Coordonner l'activité d'une équipe</li>
                                        <li> Concevoir les modalités de prestation et les conditions de réalisation de transport avec la clientèle ou les prestataires</li>
                                        <li>Mener des opérations de transport en relation avec une clientèle internationale</li>
                                        <li>Organiser et coordonner le circuit des informations avec les autres services</li>
                                        <li>Analyser les données d'activité du service et identifier des axes d'amélioration</li>
                                        <li>Suivre un budget</li>
                                        <li>Traiter des dossiers de contentieux (litiges, réclamations ...)</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>AVRIL 2013 <br />
                                    à <br />
                                    MARS 2018</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>ORGANISATEUR TRANSPORT INTERNATIONAL</h3>
                                    <div class="date">AVRIL 2013 à MARS 2018</div>
                                    <div class="place">Stefover Vitrolles (13)</div>

                                    <ul>
                                        <li>Conseiller un client sur la circulation internationale des marchandises</li>
                                        <li>Codifier la marchandise à partir du descriptif fourni par le client</li>
                                        <li>Collecter les documents d'expédition de la marchandise et constituer le dossier de la prestation (transit, douane)</li>
                                        <li>Réaliser et contrôler les documents liés à la circulation internationale de la marchandise (facture douanière, Déclaration Administrative Unique -DAU-, lettre de crédit, ...)</li>
                                        <li>Suivre l'acheminement des marchandises, informer le client sur le déroulement et présenter des solutions en cas d'anomalies</li>
                                        <li>Rechercher des informations documentaires</li>
                                        <li>Gérer l'activité logistique</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>JAN 2010 <br />
                                    à <br />
                                    AVRIL 2013</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>RESPONSABLE SERVICE RORO MAGHREB</h3>
                                    <div class="date">JAN 2010 à AVRIL 2013</div>
                                    <div class="place">Leon Vincent Overseas Marseille (13)</div>

                                    <ul>
                                        <li>Supervise et coordonne l'activité du service d'exploitation de transport régional et portuaire dans ses dimensions techniques, selon la réglementation du transport international, les règles de sécurité et dans un objectif de qualité (service, coût, délais).</li>
                                        <li>En lien avec le GPMM (Port autonome de Marseille)</li>
                                        <li>Dirige des équipes d'un site d'exploitation (techniciens exploitants, conducteurs, agents de quai, ...).</li>
                                        <li>Superviser les plannings du service à partir des carnets de commande</li>
                                        <li>Coordonner l'activité d'une équipe</li>
                                        <li> Concevoir les modalités de prestation et les conditions de réalisation de transport avec la clientèle ou les prestataires</li>
                                        <li>Mener des opérations de transport en relation avec une clientèle internationale</li>
                                        <li>Organiser et coordonner le circuit des informations avec les autres services</li>
                                        <li>Analyser les données d'activité du service et identifier des axes d'amélioration</li>
                                        <li>Suivre un budget</li>
                                        <li>Traiter des dossiers de contentieux (litiges, réclamations ...)</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>JUILLET 2004<br />
                                    à <br />
                                    JAN 2010</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>AGENT DE TRANSIT IMPORT/EXPORT</h3>
                                    <div class="date">JUILLET 2004 à JAN 2010</div>
                                    <div class="place">Leon Vincent Overseas Marseille (13)</div>

                                    <ul>
                                        <li>Conseiller un client sur la circulation internationale des marchandises</li>
                                        <li>Codifier la marchandise à partir du descriptif fourni par le client</li>
                                        <li>Collecter les documents d'expédition de la marchandise et constituer le dossier de la prestation (transit, douane)</li>
                                        <li>Réaliser et contrôler les documents liés à la circulation internationale de la marchandise (facture douanière, Déclaration Administrative Unique -DAU-, lettre de crédit, ...)</li>
                                        <li>Suivre l'acheminement des marchandises, informer le client sur le déroulement et présenter des solutions en cas d'anomalies</li>
                                        <li>Rechercher des informations documentaires</li>
                                        <li>Gérer l'activité logistique</li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    </div>

                    <div class="divscolaire">
                        <div id="scolaire" class="scolaire">👨🏽‍🎓 Formation</div>
                    </div>
                    <div class="separation"></div>

                    <div id="cest_scolaire" class="cest_scolaire">
                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MAI 2021 <br />
                                    à <br />
                                    SEPT 2021</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : DEVELOPPEUR INTEGRATEUR EN REALISATION D’APPLICATIONS WEB (Titre Professionnel Niveau III)</h3>
                                    <div class="date">MAI 2021 à SEPT 2021</div>
                                    <div class="place">3W Academy Marseille (13)</div>

                                    <ul>
                                        <li>Etude et utilisation des langages HTML 5, CSS 3, PHP 7, SQL, JavaScript, Ajax, JQuery pour la création complète de sites internet.</li>
                                        <li>Etude et réalisation de maquettes responsives . Etude et conception de base de données MySQL.</li>
                                        <li>Respect des bonnes pratiques de développement.</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>SEPT 2013</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : ATTESTATIONS DE CAPACITE PROFESSIONNELLE TRANPORT ROUTIER ET COMMISSIONNAIRE EN TRANSPORT</h3>
                                    <div class="date">SEPT 2013</div>
                                    <div class="place">DREAL Marseille (13)</div>
                                </div>
                            </div>
                        </article>

                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>2002 <br />
                                    à <br />
                                    2004</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : BTS TRANSPORT</h3>
                                    <div class="date">2002 à 2004</div>
                                    <div class="place">CFA Salon de Provence(13)</div>

                                    <ul>
                                        <li>Transport internationnal</li>
                                        <li>Douanes</li>
                                        <li>Transport routier, maritime, aérien, ferroviaire</li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>

        <section class="contact">
            <article>
                <div class="form_contact">
                    <h2 class="sec04 titre_homepage">Contact.</h2>
                    <p>🙋🏽‍♂️ Restons en contact.</p>
                    <div class="separation"></div>
                    <form action="index.php?controller=contact&action=save_messages" method="POST" class="form_return revelation animation fadeInUp" id="form">

                        <small class="small_error_nom"></small>
                        <input type="text" name="nom" id="nom" placeholder="Nom.">

                        <small class="small_error_prenom"></small>
                        <input type="text" name="prenom" id="prenom" placeholder="Prénom.">

                        <small class="small_error_mail"></small>
                        <input type="email" name="email" id="email" placeholder="Email.">

                        <small class="small_error_message"></small>
                        <textarea name="message" id="message" placeholder="Message."></textarea>

                        <button type="submit" name="valider" id="bouton_validation">Envoyer</button>
                    </form>
                </div>
                <div class="message_sent">
                    <span>Merci.</span>
                    <p>Message envoyé.</p>
                </div>
            </article>
        </section>
    </main>