<main>
        <section class="presentation">
            <h2 class="sec01 sec05 titre_homepage"><?= $presentation->titre ?>.</h2>
            <p>🦸🏽‍♂️ Un petit résumé.</p>
            <div class="separation"></div>
            <article>
                <div class="photo revelation fadeInLeft">
                    <img src="img/MeBlack.jpg" alt="Photo de Omar Belaid">
                </div>
                <div class="text revelation fadeInRight">
                    <p><?= $presentation->contenu ?></p>
                </div>
            </article>
        </section>

        <section class="competences">
            <h2 class="sec02 titre_homepage">Mes compétences.</h2>
            <p>👨🏽‍🔧 A votre service.</p>
            <div class="separation"></div>
            <article>
                <div>
                    <i class="devicon-html5-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-css3-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-php-plain colored revelation animation fadeInUp"></i>
                    <i class="devicon-javascript-plain colored revelation animation fadeInRight"></i>
                    <i class="devicon-jquery-plain-wordmark colored revelation animation fadeInRight"></i>
                </div>

                <div>
                    <i class="devicon-mysql-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-bootstrap-plain-wordmark colored revelation animation fadeInLeft"></i>
                    <i class="devicon-visualstudio-plain-wordmark colored revelation animation fadeInUp"></i>
                    <i class="devicon-wordpress-plain-wordmark colored revelation animation fadeInRight"></i>
                    <i class="devicon-github-plain-wordmark colored revelation animation fadeInRight"></i>
                </div>
            </article>
        </section>

        <section class="experience">
            <div class="experience_container">
                <h2 class="sec03 titre_homepage">Mon Parcours</h2>
                <div class="divpro"><span id="pro" class="pro">👷🏽‍♂️ Professionnel</span></div>
                <div class="separation"></div>

                <div id="timeline">
                    <div id="cest_professionnel" class="cest_professionnel">

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>SEPT 2021<br />
                                    à <br />
                                    AVRIL 2022</p>
                            </div>
                            <div class="right">
                                <div class="content">

                                    <h3><i class="fas fa-briefcase"></i>DÉVELOPPEUR WEB FULL-STACK</h3>
                                    <div class="date">
                                        SEPT 2021 à Ce jour
                                    </div>
                                    <div class="place">Firstcom | New Media (13)</div>


                                    <ul>
                                        <li>Ajout nouvelles fonctionnalités sur intranet et correction de bug (PHP, JS, SQL, CSS).</li>
                                        <li>Ajout nouvelles fonctionnalités sur site commerciaux, correction de bug  et maintenance (Wordpress).</li>
                                    </ul>

                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MAI 2021<br />
                                    à <br />
                                    SEPT 2021</p>
                            </div>
                            <div class="right">
                                <div class="content">

                                    <h3><i class="fas fa-briefcase"></i>DÉVELOPPEUR WEB FULL-STACK</h3>
                                    <div class="date">
                                        MAI 2021 à SEPT 2021
                                    </div>
                                    <div class="place">3W Academy Marseille (13)</div>


                                    <ul>
                                        <li>Etude et utilisation des langages HTML 5, CSS 3, PHP 7, SQL, JavaScript, Ajax, JQuery pour la création complète de sites internet.</li>
                                        <li>Etude et réalisation de maquettes responsives . Etude et conception de base de données MySQL.</li>
                                        <li>Respect des bonnes pratiques de développement.</li>
                                    </ul>

                                </div>
                            </div>
                        </article>

                        <article class="event work hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>JUIL 2004<br />
                                    à <br />
                                    SEPT 2020</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-briefcase"></i>EXPERIENCES PRECEDENTES</h3>
                                    <div class="date">JUIL 2004  à SEPT 2020</div>
                                    <div class="place">Tranport internationnal</div>

                                    <ul>
                                        <li><strong>Responsable d’exploitation chez Bansard International</strong> de Mai 2019 à Septembre 2020.</li>
                                        <li><strong>Organisateur transport international chez Stefover </strong> de Septembre 2018 à Avril 2019.</li>
                                        <li><strong>Responsable transport chez Vectorys </strong> de Mars 2018 à Aout 2018.</li>
                                        <li><strong>Organisateur transport international chez Stefover </strong> de Avril 2013 à Mars 2018.</li>
                                        <li><strong>Responsable de service chez LV Overseas</strong> de Juillet 2004 à Avril 2013.</li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    </div>

                    <div class="divscolaire">
                        <div id="scolaire" class="scolaire">👨🏽‍🎓 Formation</div>
                    </div>
                    <div class="separation"></div>

                    <div id="cest_scolaire" class="cest_scolaire">
                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>MAI 2021 <br />
                                    à <br />
                                    SEPT 2021</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : DEVELOPPEUR INTEGRATEUR EN REALISATION D’APPLICATIONS WEB (Titre Professionnel Niveau III)</h3>
                                    <div class="date">MAI 2021 à SEPT 2021</div>
                                    <div class="place">3W Academy Marseille (13)</div>

                                    <ul>
                                        <li>Etude et utilisation des langages HTML 5, CSS 3, PHP 7, SQL, JavaScript, Ajax, JQuery pour la création complète de sites internet.</li>
                                        <li>Etude et réalisation de maquettes responsives . Etude et conception de base de données MySQL.</li>
                                        <li>Respect des bonnes pratiques de développement.</li>
                                    </ul>
                                </div>
                            </div>
                        </article>

                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>SEPT 2013</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : ATTESTATIONS DE CAPACITE PROFESSIONNELLE TRANPORT ROUTIER ET COMMISSIONNAIRE EN TRANSPORT</h3>
                                    <div class="date">SEPT 2013</div>
                                    <div class="place">DREAL Marseille (13)</div>
                                </div>
                            </div>
                        </article>

                        <article class="event school hidden revelation animation fadeInDown">
                            <div class="left">
                                <p>2002 <br />
                                    à <br />
                                    2004</p>
                            </div>
                            <div class="right">
                                <div class="content">
                                    <h3><i class="fas fa-graduation-cap"></i>Diplôme : BTS TRANSPORT</h3>
                                    <div class="date">2002 à 2004</div>
                                    <div class="place">CFA Salon de Provence(13)</div>

                                    <ul>
                                        <li>Transport internationnal</li>
                                        <li>Douanes</li>
                                        <li>Transport routier, maritime, aérien, ferroviaire</li>
                                    </ul>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
        </section>

        <section class="contact">
            <article>
                <div class="form_contact">
                    <h2 class="sec04 titre_homepage">Contact.</h2>
                    <p>🙋🏽‍♂️ Restons en contact.</p>
                    <div class="separation"></div>
                    <form action="index.php?controller=contact&action=save_messages" method="POST" class="form_return revelation animation fadeInUp" id="form">

                        <small class="small_error_nom"></small>
                        <input type="text" name="nom" id="nom" placeholder="Nom.">

                        <small class="small_error_prenom"></small>
                        <input type="text" name="prenom" id="prenom" placeholder="Prénom.">

                        <small class="small_error_mail"></small>
                        <input type="email" name="email" id="email" placeholder="Email.">

                        <small class="small_error_message"></small>
                        <textarea name="message" id="message" placeholder="Message."></textarea>

                        <button type="submit" name="valider" id="bouton_validation">Envoyer</button>
                    </form>
                </div>
                <div class="message_sent">
                    <span>Merci.</span>
                    <p>Message envoyé.</p>
                </div>
            </article>
        </section>
    </main>