
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="js/header.js"></script>
        <script src="js/animation.js"></script>
        <script src="js/form.js"></script>
        <script src="js/ajaxContact.js"></script>
        <script src="js/ajaxAdminContenu.js"></script>
        <script src="js/ajaxAdminMessages.js"></script>
        <script src="js/askValid.js"></script>
        <script src="js/affichageXp.js"></script>
    <footer>
        <p>© <strong>Omar BELAID</strong></p>
        <p>
            <a href="https://www.linkedin.com/in/omar-belaid" target="_blank"><i class="fab fa-linkedin"></i></a>
        </p>
    </footer>
    </body>
</html> 