        <footer>
            <p>© <strong>Page administrateur Omar BELAID</strong></p>
        </footer>

        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="../js/header.js"></script>
        <script src="../js/animation.js"></script>
        <script src="../js/adminForm.js"></script>
        <script src="../js/ajaxAdminContenu.js"></script>
        <script src="../js/ajaxAdminMessages.js"></script>
        <script src="../js/askValid.js"></script>
        </body>

        </html>